name: 🐞 Bug report
description: Report a bug or an issue.
title: 'bug: '
labels: ['Bug report']
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
          <picture>
            <source
              width="256px"
              media="(prefers-color-scheme: dark)"
              srcset="https://raw.githubusercontent.com/LuisCupul04/extenre-patches-gradle-plugin/master/ExtenRe-Red.svg"
            >
          </picture>

        # ReVanced Patches Gradle plugin bug report

        Before creating a new bug report, please keep the following in mind:

        - **Do not submit a duplicate bug report**: Search for existing bug reports [here](https://github.com/LuisCupul04/extenre-patches-gradle-plugin/issues?q=label%3A%22Bug+report%22).
        - **Do not use the issue page for support**: If you need help or have questions, check out other platforms
  - type: textarea
    attributes:
      label: Bug description
      description: |
        - Describe your bug in detail
        - Add steps to reproduce the bug if possible (Step 1. ... Step 2. ...)
        - Add images and videos if possible
    validations:
        required: true
  - type: textarea
    attributes:
      label: Error logs
      description: Stack traces, error messages, and logs are helpful to understand the bug.
      render: shell
  - type: textarea
    attributes:
      label: Solution
      description: If applicable, add a possible solution to the bug.
  - type: textarea
    attributes:
      label: Additional context
      description: Add additional context here.
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your bug report will be closed if you don't follow the checklist below.
      options:
        - label: I have checked all open and closed bug reports and this is not a duplicate.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
